services:
  php-apache:
    build: .
    container_name: php_server
    ports:
      - "8089:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=Rain
      - MYSQL_PASSWORD=Sunny
      - MYSQL_DB=app_db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: Rain
      MYSQL_PASSWORD: Sunny
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
